# Generated by Django 2.1.5 on 2019-09-29 03:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190927_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_posted',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Body',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='p_file',
            new_name='question_file',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='p_image',
            new_name='question_image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_file',
            field=models.FileField(blank=True, null=True, upload_to='comment_files'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_pics'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 3, 44, 58, 920581, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 3, 44, 58, 919583, tzinfo=utc)),
        ),
    ]
