# Generated by Django 2.1.5 on 2019-09-29 03:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190929_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 3, 45, 36, 259251, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 3, 45, 36, 259251, tzinfo=utc)),
        ),
    ]
